config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    find
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(user_params)
    redirect_to article_path(@article)
  end

  def edit
    find
  end

  def update
    find
    @article.update(user_params)
    redirect_to article_path(@article)
  end

  def destroy
    find
    @article.destroy
    redirect_to articles_path(@articles)
  end

  private

  def find
    @article = Article.find(params[:id])
  end

  def user_params
    params.require(:article).permit([:title, :content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>The Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %>
      <%= link_to '🗑', article_path(article),
      method: :delete,
      data: { confirm: "Are you sure??" } %>
    </li>
  <% end %>
</ul>

<%= link_to 'add new article', new_article_path(@article) %>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %> <%= link_to '✏️', edit_article_path(@article) %><%= link_to '🗑', article_path(@article),
      method: :delete,
      data: { confirm: "Are you sure??" } %></h1>
<h2><%= @article.content %></h2>

<%= link_to 'go to the home', articles_path(@articles) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>